INFO - 
üß™ Starting test: test_authenticated_users_can_read_blogs
INFO - ====== WebDriver manager ======
INFO - Get LATEST edgedriver version for Edge 137.0.3296
INFO - Get LATEST edgedriver version for Edge 137.0.3296
INFO - Driver [C:\Users\Dell\.wdm\drivers\edgedriver\win64\137.0.3296.93\msedgedriver.exe] found in cache
INFO - Edge WebDriver created successfully
INFO - Driver configured with timeouts - Implicit: 3s, Page load: 10s, Explicit: 8s
INFO - Attempting login with email: consultant1@gencare.com
INFO - Navigating to: http://localhost:5173/
INFO - Clicked element: ('xpath', "//button[contains(text(), 'ƒêƒÉng nh·∫≠p')]")
INFO - Login modal opened successfully
INFO - Typed text into ('name', 'email'): consultant1@gencare.com
INFO - Typed text into ('name', 'password'): password
INFO - Clicked element: ('xpath', "//button[@type='submit' and contains(text(), 'ƒêƒÉng nh·∫≠p')]")
ERROR - Login failed: 
INFO - WebDriver quit successfully
WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001830697A210>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/db73f0b799dd77822277bcf1e42f0bc9/element
WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000018306979F70>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/db73f0b799dd77822277bcf1e42f0bc9/element
WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001830697AED0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/db73f0b799dd77822277bcf1e42f0bc9/element
ERROR - Exception during logout: HTTPConnectionPool(host='localhost', port=53179): Max retries exceeded with url: /session/db73f0b799dd77822277bcf1e42f0bc9/element (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000018306978F80>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
INFO - ‚úÖ Test completed: test_authenticated_users_can_read_blogs
