{"name": "test_invalid_credentials", "status": "passed", "description": "Test login with invalid credentials", "attachments": [{"name": "log", "source": "bfd04ec4-27f9-4600-9263-cecc0cb00be3-attachment.txt", "type": "text/plain"}, {"name": "stdout", "source": "f210bdaf-cebf-4ece-85f7-8b3fb98b860f-attachment.txt", "type": "text/plain"}, {"name": "stderr", "source": "eb556dcd-6fae-40b4-8463-b807012a251a-attachment.txt", "type": "text/plain"}], "start": 1750604177134, "stop": 1750604199425, "uuid": "d2975ac0-ebb4-4603-90e5-7670d8aa8849", "historyId": "58402997d9f56d988b288fd3b3ca707c", "testCaseId": "58402997d9f56d988b288fd3b3ca707c", "fullName": "tests.test_simple_auth.TestSimpleAuth#test_invalid_credentials", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_simple_auth"}, {"name": "subSuite", "value": "TestSimpleAuth"}, {"name": "host", "value": "DESKTOP-E4KF9OU"}, {"name": "thread", "value": "34016-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_simple_auth"}]}