{"name": "test_invalid_credentials", "status": "failed", "statusDetails": {"message": "AssertionError: Should remain on login page\nassert '/login' in 'http://localhost:5173/'\n +  where 'http://localhost:5173/' = <bound method BasePage.get_current_url of <pages.login_page.LoginPage object at 0x000001FA638B3AA0>>()\n +    where <bound method BasePage.get_current_url of <pages.login_page.LoginPage object at 0x000001FA638B3AA0>> = <pages.login_page.LoginPage object at 0x000001FA638B3AA0>.get_current_url\n +      where <pages.login_page.LoginPage object at 0x000001FA638B3AA0> = <test_authentication.TestAuthentication object at 0x000001FA638858E0>.login_page", "trace": "tests\\test_authentication.py:95: in test_invalid_credentials\n    assert \"/login\" in self.login_page.get_current_url(), \"Should remain on login page\"\nE   AssertionError: Should remain on login page\nE   assert '/login' in 'http://localhost:5173/'\nE    +  where 'http://localhost:5173/' = <bound method BasePage.get_current_url of <pages.login_page.LoginPage object at 0x000001FA638B3AA0>>()\nE    +    where <bound method BasePage.get_current_url of <pages.login_page.LoginPage object at 0x000001FA638B3AA0>> = <pages.login_page.LoginPage object at 0x000001FA638B3AA0>.get_current_url\nE    +      where <pages.login_page.LoginPage object at 0x000001FA638B3AA0> = <test_authentication.TestAuthentication object at 0x000001FA638858E0>.login_page"}, "description": "Test login with invalid credentials", "steps": [{"name": "Testing invalid email and password combination", "status": "failed", "statusDetails": {"message": "AssertionError: Should remain on login page\nassert '/login' in 'http://localhost:5173/'\n +  where 'http://localhost:5173/' = <bound method BasePage.get_current_url of <pages.login_page.LoginPage object at 0x000001FA638B3AA0>>()\n +    where <bound method BasePage.get_current_url of <pages.login_page.LoginPage object at 0x000001FA638B3AA0>> = <pages.login_page.LoginPage object at 0x000001FA638B3AA0>.get_current_url\n +      where <pages.login_page.LoginPage object at 0x000001FA638B3AA0> = <test_authentication.TestAuthentication object at 0x000001FA638858E0>.login_page\n", "trace": "  File \"D:\\Ky5\\SWP\\Group3SWP\\selenium-tests\\tests\\test_authentication.py\", line 95, in test_invalid_credentials\n    assert \"/login\" in self.login_page.get_current_url(), \"Should remain on login page\"\n"}, "start": 1750604396557, "stop": 1750604408012}], "attachments": [{"name": "Failed Test Screenshot", "source": "b7fcf81f-7962-408f-bcc6-e0fbe37db9e1-attachment.png", "type": "image/png"}, {"name": "log", "source": "483d8fd1-699c-44b4-bd10-4f8c90037651-attachment.txt", "type": "text/plain"}, {"name": "stdout", "source": "f9f48afb-b421-40dd-8d87-673aa00eee92-attachment.txt", "type": "text/plain"}, {"name": "stderr", "source": "0a51178c-393f-437b-a991-b362dcfc9977-attachment.txt", "type": "text/plain"}], "start": 1750604396556, "stop": 1750604408013, "uuid": "233b7d98-d4a4-465c-ae49-d6bad34f4d8e", "historyId": "b52d9931c78f5bb4bf2fcc630efa397d", "testCaseId": "b52d9931c78f5bb4bf2fcc630efa397d", "fullName": "tests.test_authentication.TestAuthentication#test_invalid_credentials", "labels": [{"name": "epic", "value": "GenCare Authentication"}, {"name": "feature", "value": "User Authentication & Authorization"}, {"name": "story", "value": "Invalid Login Tests"}, {"name": "severity", "value": "high"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_authentication"}, {"name": "subSuite", "value": "TestAuthentication"}, {"name": "host", "value": "DESKTOP-E4KF9OU"}, {"name": "thread", "value": "41244-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_authentication"}]}