{"name": "test_invalid_credentials", "status": "passed", "description": "Test login with invalid credentials", "attachments": [{"name": "log", "source": "9ae99ac2-152f-47a1-95c0-fc683a5cd8c4-attachment.txt", "type": "text/plain"}, {"name": "stdout", "source": "fcf55f06-35b9-4caa-92ae-106a20dd0bb3-attachment.txt", "type": "text/plain"}, {"name": "stderr", "source": "827d1428-a093-4f03-bc5d-56abca757d6a-attachment.txt", "type": "text/plain"}], "start": 1750604525150, "stop": 1750604547236, "uuid": "7d0ffd38-9496-46d4-a372-016dc36008a6", "historyId": "58402997d9f56d988b288fd3b3ca707c", "testCaseId": "58402997d9f56d988b288fd3b3ca707c", "fullName": "tests.test_simple_auth.TestSimpleAuth#test_invalid_credentials", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_simple_auth"}, {"name": "subSuite", "value": "TestSimpleAuth"}, {"name": "host", "value": "DESKTOP-E4KF9OU"}, {"name": "thread", "value": "27720-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_simple_auth"}]}