[32mINFO    [0m BlogPageNew:blog_page_new.py:90 Navigating to blog list: http://localhost:5173/blogs
[1m[31mERROR   [0m utils.wait_helpers:wait_helpers.py:80 Element not visible within 8s: ('css selector', ".blog-list, .blogs-container, [data-testid='blog-list']")
[1m[31mERROR   [0m BlogPageNew:base_page.py:117 Element not visible: ('css selector', ".blog-list, .blogs-container, [data-testid='blog-list']")
[33mWARNING [0m BlogPageNew:blog_page_new.py:596 Blog list container not found
[32mINFO    [0m utils.driver_manager:driver_manager.py:190 WebDriver quit successfully
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000183069788C0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/9f5af52410ab6c0a80e603ed3b499038/element
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000018306978BF0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/9f5af52410ab6c0a80e603ed3b499038/element
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:868 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000018306978E00>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/9f5af52410ab6c0a80e603ed3b499038/element
[1m[31mERROR   [0m LoginPage:login_page.py:414 Exception during logout: HTTPConnectionPool(host='localhost', port=53052): Max retries exceeded with url: /session/9f5af52410ab6c0a80e603ed3b499038/element (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000018306979010>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
[32mINFO    [0m TestBlogCRUD:test_blog_crud.py:37 âœ… Test completed: test_guest_can_read_blogs